import { RobotEyes,RobotHands,Dependencies } from "../../robots/wm/consolidatedReport/createTemplate"
import RoleFilter from "../../support/filter"

const robotEyes = new RobotEyes()
const robotHands = new RobotHands()
const dependencies = new Dependencies()

context('verifying the functionality of Create Template ',()=>{
    describe('Verifying the functionality of Create Template using Locations',()=> {
        RoleFilter(['smoke', 'regression'], () => {
        before('Login in to washmetrix', () => {
            cy.clearAllSessionStorage()
            cy.clearAllLocalStorage()
            cy.clearAllCookies()
            dependencies.loginWashmetrix()
            // robotHands.clicOnSignInAsButton()
            robotHands.scrollingIntoOrganisation()
            // robotHands.clicOnSignInAsButton()
            robotEyes.seesWashmetrixOrg()
            robotHands.clickOnOrg()
        })
        it('Navigating to Insights page',()=>{
            robotEyes.seesInsightsIconOnLeftNav()
            robotHands.clicksOnInsightsIcon()

        })
        it('Verifying the functionality Of Create template using Locations', ()=> {
            robotEyes.seesCreateComparisonButton()
            robotEyes.verifyingCreateCompariosnButtonText('Create Comparison')
            robotHands.clicksOnCreateComparisonButton()
            robotEyes.seesCreateComparisonHeader()
            robotEyes.verifyingTheHeaderOfCreateComparisonPopUP()
            robotEyes.seesNextButtonIsVisbile()
            robotEyes.seesNextButtonIsDisabled()
            robotEyes.seesCloseIconIsVisible()
            robotEyes.verifyingTheHeaderOfInputField()
            robotEyes.seesTemplateNameInputFiled()
            robotHands.EntersTextOnInputField('test')
            robotEyes.seesChooseComparisonHeader()
            robotEyes.VerifyingTheTextOfChooseComparisonHeader()
            robotEyes.seesLocationRadioButtonIsVisible()
            robotEyes.seesSitegroupRadioButtonIsVisible()
            robotHands.clicksOnLocationRadioButton()
            robotEyes.seesNextButtonIsEnabled()
            robotHands.clicksOnNextButton()
            robotEyes.seesHeaderLocations()
            robotEyes.verifyingTheHeaderOfLocations()
            robotEyes.seesCloseIconIsVisible()
            robotEyes.seesSearchButtonIsVisible()
            robotEyes.seesNextButtonIsDisabled()
            robotEyes.seesAllSelectionCheckBox()
            robotHands.clicksOnSelectAllCheckBox()
            robotEyes.seesNextButtonIsEnabled()
            robotEyes.seesCancelButtonIsVisible()
            robotEyes.seesBackButtonIsVisible()
            robotHands.clicksOnNextButton()
            robotEyes.seesCreateButtonIsDisabled()
            robotEyes.seesSalesAndLaborModule()
            robotHands.clicksOnSalesAndLaborModule()
            robotHands.scrollingToSeeCashVsCardMetric()
            robotHands.clicksOnCashVsCardMetricCheckbox()
            robotHands.clicksOnSalesAndLaborModule()
            robotEyes.seesMembershipModule()
            robotHands.clicksOnMembershipModule()
            robotHands.scrollingToSeeGrowthRateMetric()
            robotHands.clicksOnGrowthRateMetricCheckBox()
            robotHands.clicksOnMembershipModule()
            robotEyes.seesAccountingModule()
            robotHands.clicksOnAccountingModule()
            robotHands. scrollToSeeNOIMetric()
            robotHands.clicksOnNOIMetricCheckBox()
            robotHands.clicksOnAccountingModule()
            robotEyes.seesCreateButtonISEnabeld()
            robotEyes.seesCancelButtonIsVisible()
            robotEyes.seesBackButtonIsVisible()
            robotEyes.seesCloseIconIsVisible()
            robotEyes.seesSearchButtonIsVisible()
            robotHands.clicksOnCancelButton()
        })
    })

    })
    RoleFilter(['regression'], () => {
        describe('verifying the functionlaity of create template using Site groups',() => {
            it('Verifying the functionality Of Create template using Locations', ()=> {
                robotEyes.seesCreateComparisonButton()
                robotEyes.verifyingCreateCompariosnButtonText('Create Comparison')
                robotHands.clicksOnCreateComparisonButton()
                robotEyes.seesCreateComparisonHeader()
                robotEyes.verifyingTheHeaderOfCreateComparisonPopUP()
                robotEyes.seesNextButtonIsVisbile()
                robotEyes.seesNextButtonIsDisabled()
                robotEyes.seesCloseIconIsVisible()
                robotEyes.verifyingTheHeaderOfInputField()
                robotEyes.seesTemplateNameInputFiled()
                robotHands.EntersTextOnInputField('test')
                robotEyes.seesChooseComparisonHeader()
                robotEyes.VerifyingTheTextOfChooseComparisonHeader()
                robotEyes.seesLocationRadioButtonIsVisible()
                robotEyes.seesSitegroupRadioButtonIsVisible()
                // robotHands.clicksOnLocationRadioButton()
                robotHands.clicksOnSiteGroupRadioButton()
                robotEyes.seesNextButtonIsEnabled()
                robotHands.clicksOnNextButton()
                // robotEyes.seesHeaderLocations()
                robotEyes.seesHeaderOfSiteGroups()
                robotEyes.verifyingTheHeaderOfSiteGroups()
                // robotEyes.verifyingTheHeaderOfLocations()
                robotEyes.seesCloseIconIsVisible()
                robotEyes.seesSearchButtonIsVisible()
                robotEyes.seesNextButtonIsDisabled()
                robotEyes.seesAllSelectionCheckBox()
                robotHands.clicksOnSelectAllCheckBox()
                robotEyes.seesNextButtonIsEnabled()
                robotEyes.seesCancelButtonIsVisible()
                robotEyes.seesBackButtonIsVisible()
                robotHands.clicksOnNextButton()
                robotEyes.seesCreateButtonIsDisabled()
                robotEyes.seesSalesAndLaborModule()
                robotHands.clicksOnSalesAndLaborModule()
                robotHands.scrollingToSeeCashVsCardMetric()
                robotHands.clicksOnCashVsCardMetricCheckbox()
                robotHands.clicksOnSalesAndLaborModule()
                robotEyes.seesMembershipModule()
                robotHands.clicksOnMembershipModule()
                robotHands.scrollingToSeeGrowthRateMetric()
                robotHands.clicksOnGrowthRateMetricCheckBox()
                robotHands.clicksOnMembershipModule()
                robotEyes.seesAccountingModule()
                robotHands.clicksOnAccountingModule()
                robotHands. scrollToSeeNOIMetric()
                robotHands.clicksOnNOIMetricCheckBox()
                robotHands.clicksOnAccountingModule()
                robotEyes.seesCreateButtonISEnabeld()
                robotEyes.seesCancelButtonIsVisible()
                robotEyes.seesBackButtonIsVisible()
                robotEyes.seesCloseIconIsVisible()
                robotEyes.seesSearchButtonIsVisible()
                robotHands.clicksOnCancelButton()
            })

        })

    })
})