import { RobotEyes,RobotHands,Dependencies } from "../../robots/wm/consolidatedReport/createTemplate"
import RoleFilter from "../../support/filter"

const robotEyes = new RobotEyes()
const robotHands = new RobotHands()
const dependencies = new Dependencies()

context('verifying the functionality of Edit Template',()=>{
    describe('Verifying the functionality of Edit Template',()=> {
        RoleFilter(['smoke', 'regression'], () => {
            before('Login in to washmetrix', () => {
                cy.clearAllSessionStorage()
                cy.clearAllLocalStorage()
                cy.clearAllCookies()
                dependencies.loginWashmetrix()
                // robotHands.clicOnSignInAsButton()
                robotHands.scrollingIntoOrganisation()
                // robotHands.clicOnSignInAsButton()
                robotEyes.seesWashmetrixOrg()
                robotHands.clickOnOrg()
            })

            it('Navigating to Insights page',()=>{
                robotEyes.seesInsightsIconOnLeftNav()
                robotHands.clicksOnInsightsIcon()

            })
            it('Verifying the functionality Of Edit template', ()=> {
                robotHands.scrollingToSeeThreeeDotMenu()
                robotEyes.seesVerticalThreeDotMenuVisible()
                robotHands.clicksOnThreeDotVerticalMenu()
                robotEyes.seesEditTemplateOptionVisible()
                robotHands.clicksOnEditTemplateButton()
                robotEyes.seesEditComaprisonHeader()
                robotEyes.verifyingTheHeaderOfEditComparisonPopUp()
                robotEyes.seesNextButtonIsVisbile()
                robotEyes.seesCloseIconIsVisible()
                robotEyes.verifyingTheHeaderOfInputField()
                robotEyes.seesTemplateNameInputFiled()
                robotHands.EntersTextOnInputField('test')
                robotEyes.seesChooseComparisonHeader()
                robotEyes.VerifyingTheTextOfChooseComparisonHeader()
                // robotEyes.seesEditPopUp()
                cy.get('input[value="LOCATION"]').then(($locations) => {
                    if($locations.is(':checked')) {
                        robotEyes.seesLocationRadioButtonIsVisible()
                        robotEyes.seesNextButtonIsEnabled()
                        robotHands.clicksOnNextButton()
                        robotEyes.seesHeaderLocations()
                        robotEyes.verifyingTheHeaderOfLocations()
                        robotEyes.seesCloseIconIsVisible()
                        robotEyes.seesSearchButtonIsVisible()
                        robotEyes.seesNextButtonIsEnabled()
                        robotHands.clicksOnSelectAllCheckBox()
                        robotEyes.seesAllSelectionCheckBox()
                        robotHands.clicksOnSelectAllCheckBox()
                        robotHands.clikcsOnSecondLocationCheckBox()
                        robotEyes.seesNextButtonIsEnabled()
                        robotEyes.seesCancelButtonIsVisible()
                        robotEyes.seesBackButtonIsVisible()
                        robotHands.clicksOnNextButton()
                        // robotEyes. seesSaveButtonIsDisabled()
                        robotEyes.seesSalesAndLaborModule()
                        robotHands.clicksOnSalesAndLaborModule()
                        robotHands.scrollingToSeeCashVsCardMetric()
                        robotHands.clicksOnCashVsCardMetricCheckbox()
                        robotHands.clicksOnSalesAndLaborModule()
                        robotEyes.seesMembershipModule()
                        robotHands.clicksOnMembershipModule()
                        robotHands.scrollingToSeeGrowthRateMetric()
                        robotHands.clicksOnGrowthRateMetricCheckBox()
                        robotHands.clicksOnMembershipModule()
                        robotEyes.seesAccountingModule()
                        robotHands.clicksOnAccountingModule()
                        robotHands. scrollToSeeNOIMetric()
                        robotHands.clicksOnNOIMetricCheckBox()
                        robotHands.clicksOnAccountingModule()
                        robotEyes.seesSaveButtonISEnabeld()
                        robotEyes.seesCancelButtonIsVisible()
                        robotEyes.seesBackButtonIsVisible()
                        robotEyes.seesCloseIconIsVisible()
                        robotEyes.seesSearchButtonIsVisible()
                        robotHands.clicksOnCancelButton()

                    } else {
                        robotEyes.seesSitegroupRadioButtonIsVisible()
                        robotEyes.seesNextButtonIsEnabled()
                        robotHands.clicksOnNextButton()
                        robotEyes.seesHeaderOfSiteGroups()
                        robotEyes.verifyingTheHeaderOfSiteGroups()
                        robotEyes.seesCloseIconIsVisible()
                        robotEyes.seesSearchButtonIsVisible()
                        robotEyes.seesNextButtonIsEnabled()
                        robotHands.clicksOnSelectAllCheckBox()
                        robotEyes.seesAllSelectionCheckBox()
                        robotHands.clicksOnSelectAllCheckBox()
                        robotHands.clikcsOnSiteGroupCheckBox()
                        robotEyes.seesNextButtonIsEnabled()
                        robotEyes.seesCancelButtonIsVisible()
                        robotEyes.seesBackButtonIsVisible()
                        robotHands.clicksOnNextButton()
                        // robotEyes. seesSaveButtonIsDisabled()
                        robotEyes.seesSalesAndLaborModule()
                        robotHands.clicksOnSalesAndLaborModule()
                        robotHands.scrollingToSeeCashVsCardMetric()
                        robotHands.clicksOnCashVsCardMetricCheckbox()
                        robotHands.clicksOnSalesAndLaborModule()
                        robotEyes.seesMembershipModule()
                        robotHands.clicksOnMembershipModule()
                        robotHands.scrollingToSeeGrowthRateMetric()
                        robotHands.clicksOnGrowthRateMetricCheckBox()
                        robotHands.clicksOnMembershipModule()
                        robotEyes.seesAccountingModule()
                        robotHands.clicksOnAccountingModule()
                        robotHands. scrollToSeeNOIMetric()
                        robotHands.clicksOnNOIMetricCheckBox()
                        robotHands.clicksOnAccountingModule()
                        robotEyes.seesSaveButtonISEnabeld()
                        robotEyes.seesCancelButtonIsVisible()
                        robotEyes.seesBackButtonIsVisible()
                        robotEyes.seesCloseIconIsVisible()
                        robotEyes.seesSearchButtonIsVisible()
                        robotHands.clicksOnCancelButton()
                        
                    }

                })
            })
            
            
        })
    })
})