import { RobotEyes,RobotHands,Dependencies } from "../../robots/wm/consolidatedReport/ui"
import RoleFilter from "../../support/filter";
import getMonthAndYear from "../../support/getMonthAndYear"

const robotEyes = new RobotEyes()
const robotHands = new RobotHands()
const dependencies = new Dependencies()
const date = getMonthAndYear
const currentDate = new Date()
const currentYear = currentDate.getFullYear()


context('Verifying the functionality of Insights', ()=> {
    describe('Verifying the UI elements of Insights', ()=>{
        RoleFilter(['smoke', 'regression'], () => {
			before('Login in to washmetrix', () => {
				cy.clearAllSessionStorage()
				cy.clearAllLocalStorage()
				cy.clearAllCookies()
				dependencies.loginWashmetrix()
				// robotHands.clicOnSignInAsButton()
				robotHands.scrollingIntoOrganisation()
				// robotHands.clicOnSignInAsButton()
				robotEyes.seesWashmetrixOrg()
				robotHands.clickOnOrg()
			})
		 
            it('Navigating to Insights page',()=>{
                robotEyes.seesInsightsIconOnLeftNav()
                robotHands.clicksOnInsightsIcon()
                robotEyes.seesHeaderOfInsights()

            })
            it('verifing Header and Orgtitle of the Insights', ()=>{
                robotEyes.verifiesInsightsHeader('Insights')
                robotEyes.sessDefaultDateNextToInsightsHeader()
                // robotEyes.verifyingDefaultDateNextToInsightsHeader(date)
                robotEyes.seesOrgName()
                robotEyes.verifiesOrgName(Cypress.env('orgName'))
            })
        })
        RoleFilter(['smoke', 'regression'], () => {
            it('verifying the functionality of  Template DropDown',() => {
                robotEyes.seesTempalteDropDown()
                robotEyes.verifyingtheDefaultTemplateWithParameterDefault('Default')
                robotEyes.seesDropDownOnIconTemplateDropDown()
                robotHands.clicksOnTemplateDropDown()
                robotEyes.seesDropDownList()
                robotHands.clicksOnDefaulttemplate()
            //     robotHands.closingTemplateDropDown()
            })
            it('Verifying the context of table',() => {
                robotEyes.seesTableColumnHeaders('Modules/KPIs','All Sites')
                robotEyes.VerifyingModuleHeadersAndMetrics()
                robotEyes.seesAccordianOnSalesAndLaborMOduleHeader()
                robotHands.clickOnAccordianOnSalesAndLaborModule() 
                // robotHands.scrollingToSeeAccordianOnMembershipModule()
                robotEyes.seesAccordianOnMembershipModuleHeader()
                robotHands.clickOnAccordinaOnMembershipModule()
                // robotHands.scrollingToSeeAccordianOnAccountingModule()
                robotEyes.seesAccordianOnAccountingModuleHeader()
                robotHands.clickOnAccordianOnAcountingModule()
                robotHands.clickOnAccordianOnAcountingModule()
                robotHands.clickOnAccordinaOnMembershipModule()
                robotHands.clickOnAccordianOnSalesAndLaborModule() 

            })
        })

        RoleFilter(['smoke', 'regression'], () => {
            it('verifying the UI elements of date Picker', ()=> {
                robotHands.scrollingToSeeFrequencyDropDown()
                robotEyes.seesfrequencyDropDown()
                robotEyes.verifyingDefaultFrequency()
                robotEyes.seesDropDownIconForFrequencyDropdown()
                robotEyes.seesCalendarDropDown()
                // robotEyes.verifyingDefaultCalendarSelection(date)
                robotHands.clicksOnFrequencyDropdown()
                robotEyes.verifyingFrequenciesOnFrequencyDropDown()
                robotHands.selectMonthFrequencyInTheDropDown()
                robotHands.clicksOnCalendar()
                robotEyes.seesyearselectionInMonthCalendar()
                robotEyes.verifyingDafaultYearInCalendar(currentYear)
                robotHands.clicksOnYearDropDownOnMonthCalendarSelection()
                robotHands.selectPreviousYearOnDatePicker()
                robotHands.selectsJulyMonthInPreviousYearOnMonthCalendar()
                robotEyes.seesCancelButtonIsVisible()
                robotEyes.VerifyingTheTextOnCancelButton('Cancel')
                robotEyes.seesApplyButtonIsVisible()
                robotEyes.VerifyingTheTextOnApplyButton('Apply')
                robotHands.clicksOnApplyButton()
                robotEyes.verifyingDefaultDateNextToInsightsHeader('Jul 2023')
                robotEyes.VerifyingModuleHeadersAndMetrics()

            })
        })
        RoleFilter(['regression'], () => {
            it('verifying the functionality of date picker',()=> {
                // robotEyes.seesfrequencyDropDown()
                // robotEyes.verifiesDefaultFrequency()
                // robotEyes.seesDropDownIconForFrequencyDropdown()
                robotHands.clicksOnFrequencyDropdown()
                robotHands.selectDayFrequencyInTheDropDown()
                robotEyes.verifyingDropDownTextAfterSelectingDay('Select Day')
                robotHands.clicksOnCalendar()
                robotEyes.seesMonthDropDownOnDayCalendar()
                robotEyes.seesYearDropDownOnDayCalendar()
                robotEyes.verifyingWeekNamesInTheCalendar()
                // robotHands.clicksOnYearDropDownOnCalendarSelection()
                robotHands.clicksOnYearDropDownInDayFrequency() 
                robotHands.selectPreviousYearOnDatePicker()
                robotHands.clciksOnMonthDropDownInDayFrequency()
                robotHands.selectsFebrauaryFromTheDropDownOnDayCalendar()
                robotHands.selectsDay()
                robotEyes.seesCancelButtonIsVisible()
                robotEyes.VerifyingTheTextOnCancelButton('Cancel')
                robotEyes.seesApplyButtonIsVisible()
                robotEyes.VerifyingTheTextOnApplyButton('Apply')
                robotHands.clicksOnApplyButton()
                robotEyes.verifyingDefaultDateNextToInsightsHeader('02/22/23')
                robotEyes.VerifyingModuleHeadersAndMetrics()
                robotHands.clicksOnFrequencyDropdown()
                robotHands.selectWeekFrequencyInTheDropDown()
                robotEyes.verifyingDropDownTextAfterSelectingWeek('Select Week')
                robotHands.clicksOnCalendar()
                robotEyes.seesMonthDropDownOnWeekCalendar()
                robotEyes.seesYearDropDownOnWeekCalendar()
                robotEyes.verifyingWeekNamesInTheCalendar()
                robotHands.clicksOnYearDropDownInWeekFrequency()
                robotHands.selectPreviousYearOnDatePicker()
                robotHands.clciksOnMonthDropDownInWeekFrequency()
                robotHands.selectsFebrauaryFromTheDropDownOnWeekCalendar()
                robotHands.selectWeek()
                robotEyes.seesCancelButtonIsVisible()
                robotEyes.VerifyingTheTextOnCancelButton('Cancel')
                robotEyes.seesApplyButtonIsVisible()
                robotEyes.VerifyingTheTextOnApplyButton('Apply')
                robotHands.clicksOnApplyButton()
                robotEyes.verifyingDefaultDateNextToInsightsHeader('02/20/23 - 02/26/23')
                robotEyes.VerifyingModuleHeadersAndMetrics()
                robotHands.clicksOnFrequencyDropdown()
                robotHands.selectQuarterFrequencyInTheDropDown()
                robotEyes.verifyingDropDownTextAfterSelectingQuarter('Select Quarter')
                robotHands.clicksOnCalendar()
                robotEyes.seesyearselectionInQuarterCalendar()
                robotHands.clicksOnYearDropDownOnQuarterCalendarSelection()
                robotHands.selectPreviousYearOnDatePicker()
                robotHands.selectsQuarter()
                robotEyes.seesCancelButtonIsVisible()
                robotEyes.VerifyingTheTextOnCancelButton('Cancel')
                robotEyes.seesApplyButtonIsVisible()
                robotEyes.VerifyingTheTextOnApplyButton('Apply')
                robotHands.clicksOnApplyButton()
                robotEyes.verifyingDefaultDateNextToInsightsHeader('Q3 2023')
                robotEyes.VerifyingModuleHeadersAndMetrics()
                robotHands.clicksOnFrequencyDropdown()
                robotHands.selectYearFrequencyInTheDropDown()
                robotEyes.verifyingDropDownTextAfterSelectingYear('Select Year')
                robotHands.clicksOnCalendar()
                robotEyes.seesPreviousButtonOnYearCalendar()
                robotHands.clicksOnPreviousButtonOnTheYear()
                robotEyes.seesNextButtonOnYearCalendar()
                robotHands.clicksOnNextButtonOnYear()
                robotHands.selectsYear()
                robotEyes.seesCancelButtonIsVisible()
                robotEyes.VerifyingTheTextOnCancelButton('Cancel')
                robotEyes.seesApplyButtonIsVisible()
                robotEyes.VerifyingTheTextOnApplyButton('Apply')
                robotHands.clicksOnApplyButton()
                robotEyes.verifyingDefaultDateNextToInsightsHeader('2023')
                robotEyes.VerifyingModuleHeadersAndMetrics()
            
            })
        })

        RoleFilter(['smoke', 'regression'], () => {
            it('Verifying UI elements Of Create Compariosn button ', ()=> {
                robotEyes.seesCreateComparisonButton()
                robotEyes.verifyingCreateCompariosnButtonText('Create Comparison')
            })
            it('Verifying vertical three dot menu in consolidated Report',()=> {
                robotHands.scrollingToSeeThreeDotMenu()
                robotEyes.seesVerticalThreeDotMenuVisible()
                robotHands.clicksOnThreeDotVerticalMenu()
                robotEyes.seesExportOptionVisible()
                robotEyes.verifyingTheTextOfExportOption('Export')
                robotHands.clicksOnExportOption()
                robotHands.clicksOnThreeDotVerticalMenu()
                robotEyes.seesMarkAsDefaultOptionVisible()
                robotEyes.verifyingTheTextOfMarkAssDefaultOption('Make as default')
                robotHands.clickingOnMarkAsDefaultOPtion()
                robotHands.clicksOnThreeDotVerticalMenu()
                robotEyes.seesEditTemplateOptionVisible()
                robotEyes.verifyingTheTextOfEditTemplatetOption('Edit')

            })
        })
    })
})