import '../../support/e2e'
import {
	RobotEyes,
	RobotHands,
	Dependencies,
} from '../../robots/wm/accounting/avgNetIncomePerCar'
import RoleFilter from '../../support/filter'

const robotEyes = new RobotEyes()
const robotHands = new RobotHands()
const dependencies = new Dependencies()

context('Verifying the functionality of Avg Net Income Per Car KPI', () => {
	describe('Verifying the functionality of Avg Net Income Per Car KPI', () => {
		 RoleFilter(['smoke', 'regression'], () => {
			before('Login in to washmetrix', () => {
				cy.clearAllSessionStorage()
				cy.clearAllLocalStorage()
				cy.clearAllCookies()
				dependencies.loginWashmetrix()
				robotHands.scrollingIntoOrganisation()
				robotEyes.seesWashmetrixOrg()
				robotHands.clickOnWashmetrixCarWashOrg()
			})
			it('Navigating to Accounting Module', () => {
				robotEyes.seesAccountingIcon()
				robotHands.clickOnAccountingIcon()
			})
			it('Verifying the title of the KPI', () => {
				robotHands.scrollingIntoAvgNetIncomePerCarTile()
				robotEyes.seesTitleOfAvgNetIncomePerCar()
				robotEyes.verifyingTheTitleOfAvgNetIncomePerCarWithDefaultDatePickerFrequency('Net Income Per Car (YTD)')
			})

			it('Verifying the graph and the value of the Avg Net Income Per Car on the tile view', () => {
				robotHands.scrollingIntoAvgNetIncomePerCarTile()
				robotHands.clickOnAccountingIcon()
				robotHands.verifiyingTheTileWithDefaultFrequency(Cypress.env('AvgNetIncomePerCar'),"average_net_income_per_car")
			})
			it('Verifying the functionality of the date picker on the tile view', () => {
				robotHands.scrollingToSeeDatePicker()
				robotEyes.seesDatepickerIsVisibleOnModuleView()
				robotHands.clicksOnDatePicker()
				robotHands.selectsTrailing12OnTileView()
				robotHands.scrollingIntoAvgNetIncomePerCarTileAfterChangingTheFrequencyFromDefault()
				robotEyes.veryfingTheTitleOfAvgNetIncomePerCarTileViewAfterChangingTheFrequencyFromDefault()
			})
			it('Verifying the Avg Net Income Per Car drill-down view', () => {
				robotHands.clickOnAvgNetIncomePerCarTile()
				robotEyes.seesBacktoAccountingVisibleOnDrillDownView()	
				robotEyes.seesDatePickerIsVisibleOnDrillDownView()
				robotEyes.seesEllipsisForExportOption()
				robotEyes.seesTheTitleOfTheGraphAndTable()
				robotEyes.verifyingTheTitleOfTheGraphAndTable()
				robotEyes.seesGraphOnDrillDownView()
				robotEyes.seesTableOnDrillDownView()
				robotHands.clickOnTopNavigationBarInDrillDownView()
				robotEyes.seesTheSerchBoxAfterClickingTheTopNavigationBar()
				robotEyes.verifyingTheSerchBoxAfterClickingTheTopNavigationBarInDrillDownView()
				robotEyes.verifyingTheTopNavigationBarLocationsInDrillDownView()
				robotEyes.verifyTheCancelButtonInTheLocationInDrillDownViewForAvgNetIncomePerCar()
				robotEyes.verifyTheApplyButtonInTheLocationInDrillDownViewForAvgNetIncomePerCar()
				robotHands.clicksOnLocationDropDownApplyButton()
			})
		 })
		 RoleFilter(['regression'], () => {
			it('Verifying the context of Table', () => {
				robotEyes.verifyingTheFirstColumnHeaderOfTable('Period')
				robotEyes.seesTheSortButtonsForPeriod()
				robotEyes.verifyingTheSecondColumnHeaderOfTable('Cars (#)')
				robotEyes.seesTheSortButtonsForNoofCars()
				robotEyes.verifyingTheThirdColumnHeaderOfTable('Income ($)')
				robotEyes.seesTheSortButtonsForIncome()
				robotEyes.verifyingTheFourthColumnHeaderOfTable('COGS ($)')
				robotEyes.seesTheSortButtonsForCOGS()
				robotEyes.verifyingTheFifthColumnHeaderOfTable('Total Costs ($)')
				robotEyes.seesTheSortButtonsForTotalCosts()
				robotEyes.verifyingTheSixthColumnHeaderOfTable('Net Operating Income ($)')
				robotHands.scrollingIntoVerifyingTheContextOfHeaderOfTable()
				robotEyes.seesTheSortButtonsForNetOperatingIncome()
				robotEyes.verifyingTheSevenColumnHeaderOfTable('Net Income ($)')
				robotEyes.seesTheSortButtonsForNetIncome()
				robotEyes.verifyingTheEightColumnHeaderOfTable('Net Income Per Car ($)')
				robotEyes.seesTheSortButtonsForNetIncomePerCar()
				robotHands.clickOnDatePickerInDrillDownView()
				robotEyes.verifyTheDatePickerFrequenciesInDrillDownViewForAvgNetIncomePerCar()
				robotEyes.verifyTheCancelButtonInTheDatePickerInDrillDownViewForAvgNetIncomePerCar()
				robotEyes.verifyTheApplyButtonInTheDatePickerInDrillDownViewForAvgNetIncomePerCar()
				robotHands.clickOnYearDropDownInTheDatePicker()
				robotHands.selectYearFromTheYearDropDownInDatePicker()
				robotHands.clickOnMonthDropDownInTheDatePicker()
				robotHands.selectMonthFromTheMonthlyDropDownInDatePicker()
				robotHands.selectFirstDayInTheDateRange()
				robotHands.clickOnNextMonthIcon()
				robotHands.selectLastDayInTheDateRange()
				robotHands.clickOnApplyButton()
				robotEyes.seesFrequencyFilter()
				robotHands.clickOnFrequencyFilter()
				robotEyes.seesQuarterlyFilterOption()
				robotHands.clickOnQuarterlyFilterOption()
				robotHands.verifyingQuarterlyFrequency(Cypress.env('AvgNetIncomePerCar'))
				robotHands.clickOnFrequencyFilter()
				robotEyes.seesYearlyFilterOption()
				robotHands.clickOnYearlyFilterOption()
				robotHands.verifyingYearlyFrequency(Cypress.env('AvgNetIncomePerCar'))
				robotHands.clickOnFrequencyFilter()
				robotEyes.seesMonthlyFilterOption()
				robotHands.clickOnMonthlyFilterOption()
				robotHands.verifyingMonthlyFrequency(Cypress.env('AvgNetIncomePerCar'))
				robotEyes.verifyingStartTimeOnTheTable()
			})

			it('Verifying the functionality of sort', () => {
				robotHands.clicksOnDescendingOrderPeriodButton()
				robotHands.clicksOnAscendingOrderPeriodButton()
				robotHands.clicksOnDescendingOrderNoofCarsButton()
				robotHands.clicksOnAscendingOrderNoofCarsButton()
				robotHands.clicksOnDescendingOrderIncomeButton()
				robotHands.clicksOnAscendingOrderIncomeButton()
				robotHands.clicksOnDescendingOrderCOGSButton()
				robotHands.clicksOnAscendingOrderCOGSButton()
				robotHands.clicksOnAscendingOrderTotalCostsButton()
				robotHands.clicksOnDescendingOrderTotalCostsButton()
				robotHands.clicksOnAscendingOrderNetOperatingIncomeButton()
				robotHands.clicksOnDescendingOrderNetOperatingIncomeButton()
				robotHands.clicksOnAscendingOrderNetIncomeButton()
				robotHands.clicksOnDescendingOrderNetIncomeButton()
				robotHands.clicksOnAscendingOrderNetIncomePerCarButton()
				robotHands.clicksOnDescendingOrderNetIncomePerCarButton()

			})
			it('Verifying the functionality of Export', () => {
				robotHands.clicksOnElipsisIconOnDrillDownView()
				robotEyes.verifyingTheExportButtonIsVisible()
				robotHands.clicksOnExportOption();
			})
		 })
		 RoleFilter(['smoke', 'regression'], () => {	
			it('Verifying the functionality of Back to all sites', () => {
				robotHands.clickOnBackToAllSitesButton()
				robotEyes.verifyingTheAccountingModuleHeader()
			})
		})
	})
})
