const { defineConfig } = require('cypress')

module.exports = defineConfig({
	projectId: 'wr8kve',
	reporter: 'cypress-multi-reporters',
	reporterOptions: {
		configFile : 'cypress/reporteroptions.json'
	},
	e2e: {
		experimentalStudio: true,
		chromeWebSecurity: false,
		testIsolation: false,
		setupNodeEvents(on, config) {
			return config
		},
		env: {
			
			APP_URL: 'https://app.washmetrix.com/',
			USER_NAME: '',
			PASSWORD: '',
			BUILD_NUMBER: '',
			RUN_NUMBER: '',
			SelectedMonth1: "[data-value='Jun']",
			MonthValue: 'Jun-22',
			StartTime:"7:00 - 8:00 AM",
			EnddateOfSecondMonth: "[aria-label*='July 31st']",
			SelectOrganisation: "[alt='Alpine Wash LLC']",
			OrgTitle: "[title='Alpine Wash LLC']",
			orgName:"Alpine Wash LLC",
			INDIVIDUAL_WASH: "https://svc-prod.washmetrix.com/sales-and-labor/individual-wash",
			AVGMONTHLY:"https://svc-prod.washmetrix.com/sales-and-labor/average-monthly-sales",
			TOTALWASHSALES:"https://svc-prod.washmetrix.com/sales-and-labor/total-wash-sales",
			TOTALCARSWASHED: "https://svc-prod.washmetrix.com/sales-and-labor/total-cars-washed",
			BUSIEST_DAY:"https://svc-prod.washmetrix.com/sales-and-labor/busiest-day-of-the-week",
			AvgDailySales: "https://svc-prod.washmetrix.com/sales-and-labor/average-daily-sales",
			CashVsCard: "https://svc-prod.washmetrix.com/sales-and-labor/cash-vs-card",
			CARS_PER_LABOR_HR:"https://svc-prod.washmetrix.com/sales-and-labor/cars-per-labor-hour",
			HourlyWashVolume: "https://svc-prod.washmetrix.com/sales-and-labor/hourly-wash-volume",
			LaborPercentageofTotalSales:"https://svc-prod.washmetrix.com/sales-and-labor/labor-percentage-total-sales",
			TotalLabor:"https://svc-prod.washmetrix.com/sales-and-labor/total-labor",
			MonthlyMembershipBilling:"https://svc-prod.washmetrix.com/membership/monthly-membership-billing",
			AvgClubUseByAccounts:"https://svc-prod.washmetrix.com/membership/monthly-avg-club-use",
			NewMembershipSales:"https://svc-prod.washmetrix.com/membership/new-membership-sales",
			AvgDailyConversionRate:"https://svc-prod.washmetrix.com/membership/avg-daily-conversion-rate",
			MembershipPercentageofTotalSales:"https://svc-prod.washmetrix.com/membership/membership-percentage-of-total-sales",
			ChurnRateBtAccounts:"https://svc-prod.washmetrix.com/membership/monthly-churn-rate",
			GrowthRateBtAccounts:"https://svc-prod.washmetrix.com/membership/monthly-growth-rate",
			CaptureRate:"https://svc-prod.washmetrix.com/membership/capture-rate",
			AvgCostPerCar:"https://svc-prod.washmetrix.com/accounting/avg-cost-per-car",
			AvgNetIncomePerCar:"https://svc-prod.washmetrix.com/accounting/average-net-income-per-car",
			CurrentProfitAndLoss:"https://svc-prod.washmetrix.com/accounting/current-profit-and-loss",
			ChemicalCostPerCar:"https://svc-prod.washmetrix.com/accounting/chemical-cost-per-car",
			SuppliesCostPerCar:"https://svc-prod.washmetrix.com/accounting/supplies-cost-per-car",
			WaterCostPerCar:"https://svc-prod.washmetrix.com/accounting/water-cost-per-car",
			ElectricCostPerCar:"https://svc-prod.washmetrix.com/accounting/electric-cost-per-car",
			MAFCostPerCar:"https://svc-prod.washmetrix.com/accounting/maf-cost-per-car",
			RandMCostPerCar:"https://svc-prod.washmetrix.com/accounting/r-and-m-cost-per-car",
			DamagesCostPerCar:"https://svc-prod.washmetrix.com/accounting/damages-cost-per-car",
			LaborCostPerCar:"https://svc-prod.washmetrix.com/accounting/labor-cost-per-car-accounting",
			PAndLComparison:"https://svc-prod.washmetrix.com/accounting/profit-and-loss-comparison",
			LaborPercentageofIncome:"https://svc-prod.washmetrix.com/accounting/labor-percentage-of-income",
			ActiveMembers:"https://svc-prod.washmetrix.com/membership/membership-activity",
		},
	},
})
