import { Dependencies,RobotEyes,RobotHands } from "../../robots/wm/periodVsPeriod/pop"
import RoleFilter from "../../support/filter"
const dependencies = new Dependencies()
const robotEyes = new RobotEyes()
const robotHands = new RobotHands()

describe('verifying the Functionality of Period Vs Period Module', ()=>{
    context('verifying the functionality of Preiod over Period with Locations',()=> {
        RoleFilter(['smoke','regression'],()=>{
             before('Login in to washmetrix', () => {
                cy.clearAllSessionStorage()
                cy.clearAllLocalStorage()
                cy.clearAllCookies()
                dependencies.loginWashmetrix()
                robotHands.scrollingIntoOrganisation()
                robotEyes.seesWashmetrixOrg()
                robotHands.clickOnWashmetrixCarWashOrg()
                })
                
            it('Verifying the title and org name of the period over period page', ()=>{
                robotHands.clicksOnPeriodOverPeriodIcon()
                robotEyes.seesTitleOfThePeriodOVerPeriodPage()
                robotEyes.verifiesTheHeaderOfThePriodOverPeriodPage('Period v Period')
                robotEyes.seesTheNameOfTheOrganization()
                robotEyes.seesTheComparisonTab()
                robotEyes.verifiesTheTextForTheComparisonTab('Comparison')
            })
            it('Verifying the elements in comparison tab for locations selection', ()=> {
                robotEyes.seesFrequencyFilterDropdown()
                robotEyes.seesHeaderOfTheFrequencyFilterDropDown()
                robotEyes.verifiesHeaderOfFrequencyFilterDropDown('Frequency')
                robotEyes.seesDropDownIconOnFrequencyFilterDropDown()
                robotEyes.verifesDefaultSelectionOnFrequencyDropDown('Month')
                robotEyes.seesTheHeaderOfLocationsAndSitegroups()
                robotEyes.verifiesTextForTheHeaderOfLocationsAndSitegroups('Locations/Site Groups')
                robotEyes.veirfiesTheTextOfFirstRadioButton('Locations')
                robotEyes.verifiesTheTextOfSecondRadioButton('Site Groups')
                robotEyes.verifyingtheDefaultSelctionOfLocationRadioButton()
                robotEyes.seesLocation1ORSiteGroup1DropDown()
                robotEyes.VerifiesLocation1ORSiteGRoupDropDownHeader('Location')
                robotEyes.verifiesTheLocation1ORSiteroupDropDownDefaultText('Select Location 1')
                robotEyes.seesPeriod1DropDown()
                robotEyes.verifiesPeriod1DropDownHeader('Period 1')
                robotEyes.verifiesDefaultTextOfPeriod1('Select Period 1')
                robotEyes.seesLocation2ORSiteGroup2DropDown()
                robotEyes.veriesTheHeaderOfLocation2ORSiteGroupDropDown('Location 2')
                robotEyes.veirifiesDefaultTextOfLocation2ORSiteGroupDropDown('Select Location 2')
                robotEyes.seesDropDownForPeriod2()
                robotEyes.verifiesTheHeaderOfthePriod2('Period 2')
                robotEyes.verifiesDefaultTextOfPeriod2('Select Period 2')
                robotEyes.seesResetButton()
                robotEyes.verifiesTheTextOfReset('Reset')
                robotEyes.SeesApplyButton()
                robotEyes.verifiesTheTextOfApplyButton('Apply')

            })
            it('verifying the functionality of location ,period dropdwons and apply button',()=>{
                robotHands.clickOnLocation1ORSiteGroup1DropDown()
                robotEyes.seesLocationsOrSiteGroupsDropDownMenu()
                robotEyes. VerifiesTheSearchOptionInDropDownMenu()
                robotHands.selectsFirstOptionInTheDropDown()
                robotHands.clicksOnPeriod1DropDown()
                robotEyes.seesYearlyOptionInPeriodDropDown()
                robotHands.clickOnYearOptionInTheDropDown()
                robotEyes.seesYear2023InTheList()
                robotHands.selectsYear2023()
                robotEyes.seesMonthsInTheDatePicker()
                robotHands.selectsJune()
                robotHands.clicksOnLocation2ORSiteGroup2DropDown()
                robotEyes.seesLocationsOrSiteGroupsDropDownMenu()
                robotEyes.VerifiesTheSearchOptionInDropDownMenu()
                robotHands.selectsSecondOptionInTheDropDown()
                robotHands.selectsSecondOptionInTheDropDown()
                robotHands.clicksOnPeriod2DropDown()
                robotEyes.seesYearlyOptionInPeriodDropDown()
                robotHands.clickOnYearOptionInTheDropDown()
                robotEyes.seesYear2023InTheList()
                robotHands.selectsYear2023()
                robotEyes.seesMonthsInTheDatePicker()
                robotHands.selectsJuly()
                robotHands.clicksOnApplyButton()

            })
            it('validating the Table Headers and Metrics',()=>{
                robotEyes.VerifiesFirstColumnHeader('Modules/KPIs')
                robotEyes.verifiesSecondColumnHeader()
                robotEyes.verifiesThePeriod1Value('Jun 2023')
                robotEyes.verifiesThirdColumnHeader()
                robotEyes.verifiesThePeriod2Values('Jul 2023')
                robotHands.scrollToSeeVaraincePercentage()
                robotEyes.verifiesFourthColumnHeader('Variance')
                robotEyes.verifiesFifthColumnHeader('Variance %')
                robotHands.scrollToSeeModuleHeader()
                robotEyes.VerifyingModuleHeadersAndMetrics()
            })
        })
    })

    context('verifying the functionality of Preiod over Period with siteGroups',()=>{
        RoleFilter(['regression'],()=>{
            it('Verifying the functionality of siteGroup Radio Button', ()=>{
                robotHands.scrollToseeOrgName()
                robotHands.clickOnSiteGroupRadioButton()

            })
            it('Verifying the elements in comparison tab for site group selection', ()=> {
                robotHands.scrollToseeOrgName()
                robotEyes.seesFrequencyFilterDropdown()
                robotEyes.seesHeaderOfTheFrequencyFilterDropDown()
                robotEyes.verifiesHeaderOfFrequencyFilterDropDown('Frequency')
                robotEyes.seesDropDownIconOnFrequencyFilterDropDown()
                robotEyes.verifesDefaultSelectionOnFrequencyDropDown('Month')
                robotEyes.seesTheHeaderOfLocationsAndSitegroups()
                robotEyes.verifiesTextForTheHeaderOfLocationsAndSitegroups('Locations/Site Groups')
                robotEyes.veirfiesTheTextOfFirstRadioButton('Locations')
                robotEyes.verifiesTheTextOfSecondRadioButton('Site Groups')
                robotEyes.verifyingTheSelectionOfSiteGroupRadioButton()
                robotEyes.seesLocation1ORSiteGroup1DropDown()
                robotEyes.VerifiesLocation1ORSiteGRoupDropDownHeader('Site Group 1')
                robotEyes.verifiesTheLocation1ORSiteroupDropDownDefaultText('Select Site Group 1')
                robotEyes.seesPeriod1DropDown()
                robotEyes.verifiesPeriod1DropDownHeader('Period 1')
                robotEyes.verifiesDefaultTextOfPeriod1('Jun 2023')
                robotEyes.seesLocation2ORSiteGroup2DropDown()
                robotEyes.veriesTheHeaderOfLocation2ORSiteGroupDropDown('Site Group 2')
                robotEyes.veirifiesDefaultTextOfLocation2ORSiteGroupDropDown('Select Site Group 2')
                robotEyes.seesDropDownForPeriod2()
                robotEyes.verifiesTheHeaderOfthePriod2('Period 2')
                robotEyes.verifiesDefaultTextOfPeriod2('Jul 2023')
                robotEyes.seesResetButton()
                robotEyes.verifiesTheTextOfReset('Reset')
                robotEyes.SeesApplyButton()
                robotEyes.verifiesTheTextOfApplyButton('Apply')

            })
            it('verifying the functionality of location ,period dropdwons and apply button',()=>{
                robotHands.clickOnLocation1ORSiteGroup1DropDown()
                robotEyes.seesLocationsOrSiteGroupsDropDownMenu()
                robotEyes. VerifiesTheSearchOptionInDropDownMenu()
                robotHands.selectsFirstOptionInTheDropDown()
                robotHands.clicksOnPeriod1DropDown()
                robotEyes.seesYearlyOptionInPeriodDropDown()
                robotHands.clickOnYearOptionInTheDropDown()
                robotEyes.seesYear2023InTheList()
                robotHands.selectsYear2023()
                robotEyes.seesMonthsInTheDatePicker()
                robotHands.selectsJuly()
                robotHands.clicksOnLocation2ORSiteGroup2DropDown()
                robotEyes.seesLocationsOrSiteGroupsDropDownMenu()
                robotEyes.VerifiesTheSearchOptionInDropDownMenu()
                robotHands.selectsSecondOptionInTheDropDown()
                robotHands.selectsSecondOptionInTheDropDown()
                robotHands.clicksOnPeriod2DropDown()
                robotEyes.seesYearlyOptionInPeriodDropDown()
                robotHands.clickOnYearOptionInTheDropDown()
                robotEyes.seesYear2023InTheList()
                robotHands.selectsYear2023()
                robotEyes.seesMonthsInTheDatePicker()
                robotHands.selectsJune()
                robotHands.clicksOnApplyButton()

            })
            it('validating the Table Headers and Metrics',()=>{
                robotEyes.VerifiesFirstColumnHeader('Modules/KPIs')
                robotEyes.verifiesSecondColumnHeader()
                robotEyes.verifiesThePeriod1Value('Jul 2023')
                robotEyes.verifiesThirdColumnHeader()
                robotEyes.verifiesThePeriod2Values('Jun 2023')
                robotHands.scrollToSeeVaraincePercentage()
                robotEyes.verifiesFourthColumnHeader('Variance')
                robotEyes.verifiesFifthColumnHeader('Variance %')
                robotHands.scrollToSeeModuleHeader()
                robotEyes.VerifyingModuleHeadersAndMetrics()
            })
            it('verifying the functionality of Reset button',()=>{
                robotHands.scrollToseeOrgName()
                robotHands.clicksOnResetButton()
                robotEyes.seesFrequencyFilterDropdown()
                robotEyes.seesHeaderOfTheFrequencyFilterDropDown()
                robotEyes.verifiesHeaderOfFrequencyFilterDropDown('Frequency')
                robotEyes.seesDropDownIconOnFrequencyFilterDropDown()
                robotEyes.verifesDefaultSelectionOnFrequencyDropDown('Month')
                robotEyes.seesTheHeaderOfLocationsAndSitegroups()
                robotEyes.verifiesTextForTheHeaderOfLocationsAndSitegroups('Locations/Site Groups')
                robotEyes.veirfiesTheTextOfFirstRadioButton('Locations')
                robotEyes.verifiesTheTextOfSecondRadioButton('Site Groups')
                robotEyes.verifyingtheDefaultSelctionOfLocationRadioButton()
                robotEyes.seesLocation1ORSiteGroup1DropDown()
                robotEyes.VerifiesLocation1ORSiteGRoupDropDownHeader('Location')
                robotEyes.verifiesTheLocation1ORSiteroupDropDownDefaultText('Select Location 1')
                robotEyes.seesPeriod1DropDown()
                robotEyes.verifiesPeriod1DropDownHeader('Period 1')
                robotEyes.verifiesDefaultTextOfPeriod1('Select Period 1')
                robotEyes.seesLocation2ORSiteGroup2DropDown()
                robotEyes.veriesTheHeaderOfLocation2ORSiteGroupDropDown('Location 2')
                robotEyes.veirifiesDefaultTextOfLocation2ORSiteGroupDropDown('Select Location 2')
                robotEyes.seesDropDownForPeriod2()
                robotEyes.verifiesTheHeaderOfthePriod2('Period 2')
                robotEyes.verifiesDefaultTextOfPeriod2('Select Period 2')
                robotEyes.seesResetButton()
                robotEyes.verifiesTheTextOfReset('Reset')
                robotEyes.SeesApplyButton()
                robotEyes.verifiesTheTextOfApplyButton('Apply')
            })
        })
    })

})