import '../../support/e2e'
import {
	RobotEyes,
	RobotHands,
	Dependencies,
} from '../../robots/wm/membership/membershipSales'
import RoleFilter from '../../support/filter'

const robotEyes = new RobotEyes()
const robotHands = new RobotHands()
const dependencies = new Dependencies()

context('Verifying the functionality of New Membership Sales KPI', () => {
	describe('Verifying the functionality of New Membership Sales KPI', () => {
		RoleFilter(['smoke', 'regression'], () => {
			before('Login in to washmetrix', () => {
				cy.clearAllSessionStorage()
				cy.clearAllLocalStorage()
				cy.clearAllCookies()
				dependencies.loginWashmetrix()
				robotHands.scrollingIntoOrganisation()
				robotEyes.seesWashmetrixOrg()
				robotHands.clickOnWashmetrixCarWashOrg()
			})
			it('Navigating to Membership Module', () => {
				robotEyes.seesMembershipIcon()
				robotHands.clickOnMembershipIcon()
			})
			it('Verifying the title of the KPI', () => {
				robotHands.scrollingIntoNewMembershipSalesTile()
				robotEyes.seesTitleOfNewMembershipSales()
				robotEyes.verifyingTheTitleOfNewMembershipSalesWithDefaultDatePickerFrequency('New Membership Sales (MTD)')
			})
			it('Verifying the graph and the value of the New Membership Sales on the tile view', () => {
				robotHands.scrollingIntoNewMembershipSalesTile()
				robotHands.clickOnMembershipIcon()
				//robotHands.verifiyingTheTileWithDefaultFrequency(Cypress.env('NewMembershipSales'),'new_members_sales')
			})
			it('Verifying the functionality of the date picker on the tile view', () => {
				robotHands.scrollingToSeeDatePicker()
				robotEyes.seesDatepickerIsVisibleOnModuleView()
				robotHands.clicksOnDatePicker()
				robotHands.selectsTrailing12OnTileView()
				robotHands.scrollingIntoNewMembershipSalesTileAfterChangingTheFrequencyFromDefault()
				robotEyes.veryfingTheTitleOfNewMembershipSalesTileViewAfterChangingTheFrequencyFromDefault()
			})
			it('Verifying the New Membership Sales drill-down view', () => {
				robotHands.clickOnNewMembershipSalesTile()
				robotEyes.seesBacktoMembershipVisibleOnDrillDownView()
				robotEyes.seesTopNavigationBarIsVisibleOnDrillDownView()
				robotEyes.seesDatePickerIsVisibleOnDrillDownView()
				robotEyes.seesEllipsisForExportOption()
				robotEyes.seesTheTitleOfTheGraphAndTable()
				robotEyes.verifyingTheTitleOfTheGraphAndTable()
				robotEyes.seesGraphOnDrillDownView()
				robotEyes.seesTableOnDrillDownView()
				robotHands.clickOnTopNavigationBarInDrillDownView()
				robotEyes.seesTheSerchBoxAfterClickingTheTopNavigationBar()
				robotEyes.verifyingTheSerchBoxAfterClickingTheTopNavigationBarInDrillDownView()
				robotEyes.verifyingTheTopNavigationBarLocationsInDrillDownView()
				robotEyes.verifyTheCancelButtonInTheLocationInDrillDownViewForNewMembershipSales()
				robotEyes.verifyTheApplyButtonInTheLocationInDrillDownViewForNewMembershipSales()
				robotHands.clickOnLocationDropDownApplyButton()
			})
		 })
		 RoleFilter(['regression'], () => {
			it('Verifying the context of Table', () => {	
				robotEyes.verifyingTheFirstColumnHeaderOfTable('Period')
				robotEyes.seesTheSortButtonsForPeriod()
				robotEyes.verifyingTheSecondColumnHeaderOfTable('Members (#)')
				robotEyes.seesTheSortButtonsForMembers()
				robotEyes.verifyingTheThirdColumnHeaderOfTable('Sales ($)')
				robotEyes.seesTheSortButtonsForSales()
				robotEyes.verifyingTheFourthColumnHeaderOfTable('Avg. Ticket ($)')
				robotEyes.seesTheSortButtonsForAverageTicket()
				robotEyes.verifyingTheFifthColumnHeaderOfTable('Individual Washes (#)')
				robotEyes.seesTheSortButtonsForIndividualWashes()
				robotEyes.verifyingTheSixthColumnHeaderOfTable('Conversion Rate (%)')
				robotHands.clickOnDatePickerInDrillDownView()
				robotEyes.verifyTheDatePickerFrequenciesInDrillDownViewForNewMembershipSales()
				robotEyes.verifyTheCancelButtonInTheDatePickerInDrillDownViewForNewMembershipSales()
				robotEyes.verifyTheApplyButtonInTheDatePickerInDrillDownViewForNewMembershipSales()
				robotHands.clickOnYearDropDownInTheDatePicker()
				robotHands.selectYearFromTheYearDropDownInDatePicker()
				robotHands.clickOnMonthDropDownInTheDatePicker()
				robotHands.selectMonthFromTheMonthlyDropDownInDatePicker()
				robotHands.selectFirstDayInTheDateRange()
				robotHands.clickOnNextMonthIcon()
				robotHands.selectLastDayInTheDateRange()
				robotHands.clickOnApplyButton()
				robotEyes.seesFrequencyFilter()
				robotHands.clickOnFrequencyFilter()
				robotEyes.seesQuarterlyFilterOption()
				robotHands.clickOnQuarterlyFilterOption()
				//robotHands.verifyingQuarterlyFrequency(Cypress.env('NewMembershipSales'))
				robotHands.clickOnFrequencyFilter()
				robotEyes.seesYearlyFilterOption()
				robotHands.clickOnYearlyFilterOption()
				//robotHands.verifyingYearlyFrequency(Cypress.env('NewMembershipSales'))
				robotHands.clickOnFrequencyFilter()
				robotEyes.seesDailyFilterOption()
				robotHands.clickOnDailyFilterOption()
				// robotHands.verifyingDailyFrequency(Cypress.env('NewMembershipSales'))
				robotHands.clickOnFrequencyFilter()
				robotEyes.seesMonthlyFilterOption()
				robotHands.clickOnMonthlyFilterOption()
				// robotHands.verifyingMonthlyFrequency(Cypress.env('NewMembershipSales'))
				robotEyes.verifyingStartTimeOnTheTable()
			})
			it('Verifying the functionality of sort', () => {
				robotHands.clicksOnDescendingOrderPeriodButton()
				robotHands.clicksOnAscendingOrderPeriodButton()
				robotHands.clicksOnDescendingOrderNewMembersButton()
				robotHands.clicksOnAscendingOrderNewMembersButton()
				robotHands.clicksOnDescendingOrderNewMemSalesButton()
				robotHands.clicksOnAscendingOrderNewMemSalesButton()
				robotHands.clicksOnDescendingOrderAverageTicketButton()
				robotHands.clicksOnAscendingOrderAverageTicketButton()
				robotHands.clicksOnDescendingOrderIndividualWashesButton()
				robotHands.clicksOnAscendingOrderIndividualWashesButton()
				robotHands.clicksOnDescendingOrderConversionRateButton()
				robotHands.clicksOnAscendingOrderConversionRateButton()
			})
			it('Verifying the functionality of Export', () => {
				robotHands.clicksOnElipsisIconOnDrillDownView()
				robotEyes.verifyingTheExportButtonIsVisible()
				robotHands.clicksOnExportOption()
			})
		 })
		 RoleFilter(['smoke', 'regression'], () => {
			it('Verifying the functionality of Back to all sites', () => {
				robotHands.clickOnBackToMembershipButton()
				robotEyes.verifyingTheMembershipModuleHeader()
			})
		})
	})
})