import { RobotEyes,RobotHands,Dependencies } from "../../robots/wm/Permission/permission"
import RoleFilter from "../../support/filter"
const dependencies = new Dependencies()
const robotEyes = new RobotEyes()
const robotHands = new RobotHands()


describe('Veriffying the functionality of Permission Module',() => {
    RoleFilter(['smoke', 'regression'], () => {
        before('logging in to washmetrix', () => {
            cy.clearAllSessionStorage()
            cy.clearAllLocalStorage()
            cy.clearAllCookies()
            dependencies.loginWashmetrix()
            robotHands.scrollingIntoOrganisation()
            robotEyes.seesWashmetrixOrg()
            robotHands.clickOnWashmetrixCarWashOrg()
        })

        context('Verifying the Elements of Permission Module',() => {
            it('navigating to Configuration Page',() => {
                robotEyes.seesConfigurationICon()
                robotHands.clicksOnConfigurationIcon()
            })
            it('Verifies Title and Sub-title of configuration page',() => {
                robotEyes.seesConfiguarationPageTitle()
                robotEyes.verifeisTheConfigurationPageTitle('Configuration')
                robotEyes.seesSubtitleOfConfiguration()
                robotEyes.VerifiesSubtitleOfConfiguration('Set up your configuration details')
            })
        it('Verifies Permission Tab',() => {
                robotEyes.seesPermissionTab()
                robotEyes.verifiesTheTextOfPermissionTab('Permissions')
                robotEyes.verifiesPermissionTabIsSelected()
                robotEyes.verifiesUserTabIsNotSelected()
        })
            it('Verifies Elements of Permission table',() => {
                robotEyes.verifiesTheTitleOfPermissionTable('All Permissions')
                robotEyes.verifiesSubtextOfTitleOfPermissionTable('You can create permissions from here.')
                robotEyes.seesSearchBox()
                robotEyes.seesSearchIcon()
                robotEyes.verifiesInputFiledTextOfSearchBox('Search')
                robotEyes.seesPermissionTypeDropDown()
                robotEyes.VerifiesDefaultSelectionForPermissionTypeDropDown('All')
                robotHands.clicksOnPermissionTypeDropDown()
                robotEyes.VerifiesPermissionDropDownElements('All','Location','Module')
                robotHands.selectsAllFromThePermissionType()
                robotEyes.seesCreatePermissionButton()
                robotEyes.seesPlusButtonOnCreatePermissionButton()
                robotEyes.verifiesCreatePermissionButtonText('Create Permission')
                robotEyes.seesFirstColumn()
                robotEyes.VerifiesSecondColumnHeader('Name')
                robotEyes.verifiesThirdColumnHeader('Permission')
                robotEyes.verifiesFourthColumnHeader('Description')
                robotEyes.verifiesAllModulePermission('All Module','MODULE','All Module Permissions')
                robotEyes.verifiesAllLocationPermission('All Location','LOCATION','All Location Permissions')
            })
            
        })
    })

    context('Verifies functionality of Create Permission', () => {
        RoleFilter(['smoke', 'regression'], () => {
            it('verifles Elemenrs on Create Permission form',() => {
                robotEyes.seesCreatePermissionButton()
                robotHands.clicksOnCreatePermissionButton()
                robotEyes.verifiesTitleOfCreatePermissionForm('Create Permission')
                robotEyes.verifiesTitleOfNameInputFiled('Permission Name ')
                robotEyes.verifiesNameInputField()
                robotEyes.seesDescrpitonFieldTitle('Description')
                robotEyes.seesDescriptionFiledCharacterLimit('0 / 150')
                robotEyes.verifiesDescriptionField('Add Description')
                robotEyes.verifiesTitleOfPermissionTypeSelection('Choose Permission')
                robotEyes.verifiesLocationRadioButton('Locations')
                robotEyes.verifiesModuleRadioButton('Modules')
                robotHands.clicksOnLocationRadioButton()
                robotEyes.verifiesTitleOfDropDown('Select Locations')
                robotEyes.verifiesDefaultSelectionCountOfDropDown('0 Selected')
                robotHands.clickOnModuleRadioButton()
                robotEyes. seesDropDown()
                robotEyes.verifiesDefaultSelectionCountOfDropDown('0 Selected')
                robotEyes. seesDropDown()
                robotEyes.verifiesCreatePermissionButtonIsDisabled()
                robotEyes.VerifiesCreatePermissionButton('Create Permission')
                robotEyes.verifiesCancelButton('Cancel')
            })
            it('verifies  Functionality Of create Permission By choosing Locations', () => {
                robotHands.entersPermissionNameOnNameField('test Permission')
                robotHands.entersDescriptionONDescriptionField('Location Permissions')
                robotEyes.seesDescriptionFiledCharacterLimit('20 / 150')
                robotHands.clicksOnLocationRadioButton()
                robotHands.clicksOnDropDown()
                robotEyes.verifiesSearchBoxOnDrillDown('Search Locations')
                robotHands.selectsFirstOptionFromDropDown()
                robotHands.selectsSecondOptionFromDropDown()
                robotHands.selectsThirdOption()
                robotHands.closingDropDown()
                robotEyes.verifiesDefaultSelectionCountOfDropDown('3 Selected')
                robotEyes.verifiesCreatePermissionButtonIsEnabled()
                robotHands.clicksOnCancelButton()

            })
        })
        RoleFilter(['regression'], () => {
            it('verifies  Functionality Of create Permission By choosing Modules', () => {
                robotHands.clicksOnCreatePermissionButton()
                robotHands.entersPermissionNameOnNameField('test Permission')
                robotHands.entersDescriptionONDescriptionField('Module Permissions')
                robotEyes.seesDescriptionFiledCharacterLimit('18 / 150')
                robotHands.clickOnModuleRadioButton()
                robotEyes.verifiesTitleOfDropDown('Select Modules')
                robotHands.clicksOnDropDown()
                robotEyes.verifiesSearchBoxOnDrillDown('Search Modules')
                robotHands.selectsFirstOptionFromDropDown()
                robotHands.selectsSecondOptionFromDropDown()
                robotHands.selectsThirdOption()
                robotHands.closingDropDown()
                robotEyes.verifiesDefaultSelectionCountOfDropDown('3 Selected')
                robotEyes.verifiesCreatePermissionButtonIsEnabled()
                robotHands.clicksOnCancelButton()

            })
        })
    })
})