import { Dependencies,RobotHands,RobotEyes } from "../../robots/wm/Permission/permission"
import RoleFilter from "../../support/filter"

const dependencies = new Dependencies()
const robotHands = new RobotHands() 
const robotEyes = new RobotEyes()

describe('Verifying the Permission detail page ',()=> {
    RoleFilter(['smoke', 'regression'], () => {
        before('logging in to washmetrix', () => {
            cy.clearAllSessionStorage()
            cy.clearAllLocalStorage()
            cy.clearAllCookies()
            dependencies.loginWashmetrix()
            robotHands.scrollingIntoOrganisation()
            robotEyes.seesWashmetrixOrg()
            robotHands.clickOnWashmetrixCarWashOrg()
        })
    })
    context('Verifying the Permission detail page of all locations', ()=> {
        RoleFilter(['smoke', 'regression'], () => {
            it('Navigating to all permissions', ()=>{
                robotHands.clicksOnConfigurationIcon()
                robotHands.clicksOnAllLocationsPermission()
            })  
            it('verifying the Deatails of ALl locations permission', () => {
                robotEyes.seesPermissionDetailPageHeader()
                robotEyes.verifyingTheTitleOfPermissionDetailPage('All Location')
                robotEyes.seesSummaryField()
                robotEyes.verfyingTheTextOfSummaryHeader('Summary')
                robotEyes.verifyingTheSummaryOfPermission('03/13/23')
                robotEyes.verifyingDescriptionHeader('Description')
                robotEyes.verifyingTheDescriptionOfPermission('All Location Permissions')
                robotEyes.verifyingTheThirdFieldInThePermissionDetailPage('Locations')
                robotEyes.verifiesHeaderOfTable('Users')
                robotEyes.verifyingTheSearchBoxOfTheTable('Search')
                robotEyes. seesPermissionDropDown()
                robotHands.clicksOnUserDropdown()
                robotEyes.verifyingTheDropdownOfUserType()
                robotHands.clickOnALLOption()
                robotEyes.verifyingTheAddUserButton('Add User')
                robotEyes.veifyingTheHeaderOfFirstColumn('First Name')
                robotEyes.verifyingTheHeaderOfSecondColumn('Last Name')
                robotEyes.verifyingTheHeaderOfThirdColumn('Email Address')
                robotEyes.verifyingTheHeaderOfFourthColumn('Status')
                robotHands.scrollToSeeBackToPermissionButton()
                robotEyes.seesBackToPermissionButton()
                robotEyes.verifiesTextOfBackToPermissionButton('Back to Permissions')
                robotHands.clickOnBacktoPermissionButton()
                robotEyes.seesConfiguarationPageTitle()
            })
        })
     })

     context('Verifying the Permission detail page of all Modules', ()=> {  
        RoleFilter(['smoke', 'regression'], () => {
            it('verifying the Deatails of ALl Modules permission', () => {
                robotHands.clicksOnAllModulesPermission()
                robotEyes.seesPermissionDetailPageHeader()
                robotEyes.verifyingTheTitleOfPermissionDetailPage('All Module')
                robotEyes.seesSummaryField()
                robotEyes.verfyingTheTextOfSummaryHeader('Summary')
                robotEyes.verifyingTheSummaryOfPermission('03/13/23')
                robotEyes.verifyingDescriptionHeader('Description')
                robotEyes.verifyingTheDescriptionOfPermission('All Module Permissions')
                robotEyes.verifyingTheThirdFieldInThePermissionDetailPage('Modules')
                robotEyes.verifiesHeaderOfTable('Users')
                robotEyes.verifyingTheSearchBoxOfTheTable('Search')
                robotEyes. seesPermissionDropDown()
                robotHands.clicksOnUserDropdown()
                robotEyes.verifyingTheDropdownOfUserType()
                robotHands.clickOnALLOption()
                robotEyes.verifyingTheAddUserButton('Add User')
                robotEyes.veifyingTheHeaderOfFirstColumn('First Name')
                robotEyes.verifyingTheHeaderOfSecondColumn('Last Name')
                robotEyes.verifyingTheHeaderOfThirdColumn('Email Address')
                robotEyes.verifyingTheHeaderOfFourthColumn('Status')
                robotHands.scrollToSeeBackToPermissionButton()
                robotEyes.seesBackToPermissionButton()
                robotEyes.verifiesTextOfBackToPermissionButton('Back to Permissions')
                robotHands.clickOnBacktoPermissionButton()
                robotEyes.seesConfiguarationPageTitle()
            })
        })
     })
})