
name: Building Docker Image For Cypress and Running It

on:
  pull_request:
    branches:
      - testactions

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    env: 
      CYPRESS_QA_CONFIG: ${{ secrets.CYPRESS_QA_CONFIG }}
      APP_URL: ${{ secrets.APP_URL }}
      # USER_NAME: ${{ secrets.USER_NAME }}
      # PASSWORD: ${{ secrets.PASSWORD }} 
      

    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: node -v
      - name: reading app url
        run: echo "${APP_URL}"
      - name: Build Docker Image
        run: docker build -f dockerfile -t wm-test-cypress-image .
      

      - name: Run smoke
        run: docker run -t  -v ${GITHUB_WORKSPACE}/cypress.qa.config.js:/app/cypress.qa.config.js -e env=qa -e url=${APP_URL} -e TAGS=smoke wm-test-cypress-image