name: Building Docker Image For Cypress and Running It

on:
  pull_request:
    branches:
      - testactions

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
    APP_URL: ${{secrets.APP_URL}}
    USER_NAME: ${{USER_NAME}}
    PASSWORD: ${{PASSWORD}}

    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: node -v

      - name: Build Docker Image
        run: docker build -f dockerfile -t wm-test-cypress-image .
      

      - name: Run smoke
        run: docker run -t  -v ${GITHUB_WORKSPACE}/cypress.qa.config.js:/app/cypress.qa.config.js -e env=qa -e TAGS=smoke wm-test-cypress-image