name: Building Docker Image For Cypress and Running It

on:
  pull_request:
    branches:
      - testactions

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # env: 
    #   CYPRESS_QA_CONFIG: ${{ secrets.CYPRESS_QA_CONFIG }}
    #   APP_URL: ${{ secrets.APP_URL }}
    #   # USER_NAME: ${{ secrets.USER_NAME }}
    #   # PASSWORD: ${{ secrets.PASSWORD }} 
      

    steps:
      - uses: docker/setup-buildx-action@v1
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: node -v
      
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1  # Replace with your desired AWS region
      - name: Login to AWS ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com

      # - name: Login to AWS ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1
      # - name: build,tag and push image to Amazon ECR
      #   env:
      #     ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #     ECR_REPOSITORY: wm
      #     # IMAGE_TAG: latest
      #   run: |
      #     docker build -t wm .
      #     docker push $ECR_REGISTRY/$ECR_REPOSITORY

      - name: build,tag and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wm-cypress
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         
      
    #  docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/wm:latest


       # docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
       # docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #  docker tag wm:latest public.ecr.aws/z8m5n0c2/wm:latest
      #  docker tag wm:latest public.ecr.aws/z8m5n0c2/wm:latest
      #     docker push public.ecr.aws/z8m5n0c2/wm:latest
      # - name: Build Docker Image
      #   # run: docker build -t wm .
      #   run: |
      #     docker buildx create --use
      #     docker buildx build -t wm-cypress .
      # - name: Tagging image with ECR Repo
      #   run: docker tag wm-cypress ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/wm-cypress


      # - name: Push Docker image to ECR
      #   run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/wm-cypress

