name: Building Docker Image For Cypress and Running It

on:
  pull_request:
    branches:
      - master

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
      - run: node -v

      - name: Build Docker Image
        run: docker build -f dockerfile -t wm-test-cypress-image .
      

      - name: Run smoke
        run: sudo docker run -it  -v ${GITHUB_WORKSPACE}/cypress.qa.config.js:app/cypress.qa.config.js -e env=qa -e TAGS=smoke wm-test-cypress-image